services:
  - type: web
    name: feedsnap-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html